<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MindMap - Uniwav</title>
    <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">



    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/css/materialize.min.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="../css/styles.css" />
    <link rel="stylesheet" href="../css/custom.css" />


    <!-- Chart Add-->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  </head>
  <body >

   <div class="navbar-fixed">
      <nav class="light-blue darken-3">
    <div class="nav-wrapper">
      <a href="../" style="margin-left: 10px;" class="brand-logo"><img alt="Uniwav" height="63" src="../img/uniwav.png"></a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">
        <li><a class="modal-trigger" href="#modal1">About</a></li>
        <li><a href="."><i class="mdi-navigation-refresh right"></i>Refresh</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a class="modal-trigger" href="about.html">About</a></li>
        <li><a class="modal-trigger" href="https://pixelswap.fr/">Corentin Mors</a></li>
        <li><a class="modal-trigger" href="https://horlogeskynet.github.io/">Samuel Forestier</a></li>
        <li><a href="."><i class="mdi-navigation-refresh right"></i>Refresh</a></li>
      </ul>
    </div>
  </nav>
    </div>


    <div class="row container">
      
      <h2 class="header">MindMap</h2>
      
      <img width="100%" src="../img/mindmap-1.jpg">

      <img width="100%" src="../img/mindmap-2.jpg">

    </div>  
    



          


   



  <div class="parallax-container">
    <div class="parallax"><img src="http://upload.wikimedia.org/wikipedia/commons/7/77/Blois_30.jpg"></div>
  </div>
  
  
  
    <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>About</h4>
      <p>Welcome to our Live Time weather project.</p>
    </div>
    <div class="modal-footer">
      <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Close</a>
    </div>
  </div>
  
  
  <footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Uniwav</h5>
                <p class="grey-text text-lighten-4">INSA Centre Val de Loire Project by 1A Students</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Made by</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="https://horlogeskynet.github.io/">Samuel Forestier</a></li>
                    <li><a class="grey-text text-lighten-3" href="https://pixelswap.fr/">Corentin Mors</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2015 Uniwav
            <a class="grey-text text-lighten-4 right" href="http://www.insa-centrevaldeloire.fr/">INSA Centre Val de Loire</a>
        </div>
    </div>
</footer>
    
    <!--scripts loaded here-->
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/js/materialize.min.js"></script>
    
    <script src="../js/scripts.js"></script>
  </body>
</html>
